SELECT DISTINCT CITY
FROM STATION
WHERE 
    CITY LIKE 'a%' OR 
    CITY LIKE 'e%' OR 
    CITY LIKE 'i%' OR 
    CITY LIKE 'o%' OR
    CITY LIKE 'u%'

SELECT DISTINCT CITY
FROM STATION
WHERE 
    CITY NOT LIKE 'a%' AND
    CITY NOT LIKE 'e%' AND 
    CITY NOT LIKE 'i%' AND 
    CITY NOT LIKE 'o%' AND
    CITY NOT LIKE 'u%'