= Table.AddColumn(AddedFiscalMonth, "Fiscal_Quarter", each if [Fiscal_Month] = "01" then "Q1" else if [Fiscal_Month] = 02 then "Q1" else if [Fiscal_Month] = 03 then "Q1" else if [Fiscal_Month] = 04 then "Q2" else if [Fiscal_Month] = 05 then "Q2" else if [Fiscal_Month] = 06 then "Q2" else if [Fiscal_Month] = 07 then "Q3" else if [Fiscal_Month] = 08 then "Q3" else if [Fiscal_Month] = 09 then "Q3" else "Q4")